### ISSUE TITLE
Anchor Location for Coordinates

### ISSUE THREAD

**Issue by JoeMatulka** [NBTSolutions/Leaflet.Dialog#10]
Any chance that they would be an option to have the dialog position tied to the map instead of the viewport?

I would love to tie the Dialog to a coordinate :smiley:

**Comment by NathanMarq** [comment]
Hey @JoeMatulka 

Sorry for taking so long to respond to this!

Tying the dialog to the map instead of the viewport is a great idea! Unfortunately, right now this library is an extension of the Leaflet Control object, so it will always be built into the Leaflet Control pane, which is overlaid over the map. It would probably require an almost total rewrite to switch to extending a Leaflet "Layer" instead of a "Control".

At some point in the future I might copy that re-write into a different file (ie, Leaflet.Dialog.Map.js, within this same plugin repo), because it does sound useful - but it's not currently on any scheduled timeline. Feel free to take a shot at it yourself and submit a pull request if you think you'd want to try it!
