### ISSUE TITLE
Problem using it with React

### ISSUE THREAD

**Issue by ghost** [NBTSolutions/Leaflet.Dialog#17]
Hello I am using your dialog, it seems to work fine, however I have problem when rendering a React element on your dialog.
Here is my code.

Create your dialog
```
let dialog = L.control.dialog({
                size: [300, 300],
                anchor: [70, 0]
            });
dialog.setContent("<div id='camera-view-container'></div>")
dialog.addTo(that.mymap);

```
Then

```
ReactDOM.render(<button onClick={()=>{ alert("test" )}}>Test</button>, document.getElementById('camera-view-container'));
```

The button is shown on  your dialog, however, when I click it I don't see alert window.
Can you help me why is this behavior?

**Comment by NathanMarq** [comment]
@ghost I'm not totally familiar with React, but I've tested your "alert" example and the dialog box seems to be working when it's defined as such:

```
var runClick = () => { alert("Hello!"); };
let dialog = L.control.dialog({
                size: [300, 300],
                anchor: [70, 0]
            });
dialog.setContent("Hello! <button id='helloBtn' onclick='runClick()'>click</button>");
dialog.addTo(map);
```

The `onclick` attribute takes an expression in this case, so you'd need to run the function inside the attribute, rather than defining it there. If you were defining the click handler in JS, you would be able to pass in the function definition like this:

```
document.getElementById("helloBtn").onclick = runClick;
```

Hope this helps!
